### ISSUE TITLE
Wrong current co-plotted when highlighting current used for calibr. in ecms_calibration_curve

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#118]
When co-plotting the current used in the calibration on a plot which has been calibrated to show current density by passing the axis to `ecms_calibration_curve`, the raw current will be co-plotted. of course, the raw current needs to be used for the calculation, but I think when highlighting in the plot, it would still make sense to highlight using the current density, just for looks of the plot. or do you think that's suggestive of the function actually using the current density and thereforte misleading? @ScottSoren 

Edit: if we dont want to allow it to highlight the current density, then I think we need to disallow it/give a warning if the current axis unit is not the same

**Comment by ScottSoren** [comment]
This may be tricky, as the `ecms_calibration_curve` method plots that highlight on an axis passed to it. The information about what unit is plotted is not stored in the axis, so I'm not sure how the method could figure it out. Reading the axis label would be fragile, since the user could have changed it. Even implementation of `pint` in ixdat won't help - it would have to somehow be implemented in matplotlib! The best might just be to specify in the docstring that the axis passed to it should not have the current in [mA].

**Comment by AnnaWiniwarter** [comment]
Ok, I didn't consider that the axis doesn't know what unit is plotted on it.

"The best might just be to specify in the docstring that the axis passed to it should not have the current in [mA]." - I'm not quite sure I understand what you mean by that. Do you mean we should be more specific that it won't work if calibrated data is plotted on the axis?

What about giving a possibility of passing to the method not only what axis to highlight, but also which unit this axis uses? i.e. not rely on it to be done automatically, but give the option to modify it?

**Comment by ScottSoren** [comment]
acceptable fix for now, but see https://github.com/ixdat/ixdat/issues/130
