### ISSUE TITLE
Problem when trying to add two SpectroMSMeasurement objects

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#158]
I came accross a problem before when importing data since `SpectroMSMeasurement` was merged (we discussed this on Slack). Now I ran into it again, and it seems to be a problem when trying to add something to a `SpectroMSMeasurement`  object (I tried adding a second `SpectroMSMeasurement` or a plain `MSMeasurement`.  I suppose this is not expected and a bug? @ScottSoren?

![image](https://github.com/ixdat/ixdat/assets/96479350/26dde742-14bd-4a02-bea9-91a3592e2ba1)

**Comment by matenestor** [comment]
I am getting this error as well when I am running external tests. The problem is in `Measurement.from_dict()` where `measurement` variable is not initialized, but it is trying to be used. [Lines 225-238](https://github.com/ixdat/ixdat/blob/e66675fc4aa81c75d6e857983e5a87434c042786/src/ixdat/measurements.py#L238)

There is just a `print` in the `except` block, but it should be `raise` which would stop the program, because it failed to create a new object. And it is not a user's problem, so I am in doubt whether the message should be there in this case.

In Anna's case, this method is used internally by ixdat while creating a new object from the two. That is one thing. Then it also complain that `SpectroMeasurement` must be initialized with `spectrum_series` and `spectrum_id`, which are probably not provided when creating the `SpectroMeasurement`.

In my case, it is the tests, because some of the datasets contain mass scans and then it fails, because of [this spectra addition](https://github.com/ixdat/ixdat/blob/e66675fc4aa81c75d6e857983e5a87434c042786/src/ixdat/readers/zilien.py#L239). The exception I am getting is: `"Measurement.__init__() got an unexpected keyword argument 'ec_technique'"`

---

Looks like there is a lot of fixes to be done plus @KennethNielsen the CI is not working as intended, because it should be running the external tests and this problem would had been caught already before.

**Comment by KennethNielsen** [comment]
I agree there are obviously bugs here. Adding two `SpectroMSMeasurement`s should probably be allowed (maybe under certain constrictions), but I'm unsure if we ever decided what should happen if you add a `SpectroMSMeasurement` with a `MSMeasurement` (since they are sort of orthogonal in nature). I think this is a question that @ScottSoren already raised, but I don't think we made a decision.

@matenestor I will make a separate issue concerning the CI and look into it. It was always the intention that pre-commit and local tests would make tests based on external data optional but that they should of course always be run in CI. Thanks for catching it.

**Comment by ScottSoren** [comment]
Seems this is a priority for the next ixdat release.

I think there are a couple things to fix here, all easy to fix but hard to find:
1. `MSSpectroMeasurement.extra_column_attrs` is [{'ms_measurement': ('tspan_bg',)}](https://github.com/ixdat/ixdat/blob/71cddb1dae19e3c665139f03db2bb0bef5b93b16/src/ixdat/techniques/ms.py#L51), not [{"spectro_measurements": {"spectrum_id"}}](https://github.com/ixdat/ixdat/blob/71cddb1dae19e3c665139f03db2bb0bef5b93b16/src/ixdat/spectra.py#L713) as we want it to be. The former should be deleted anyway with the coming background overhaul. But the underlying problem is that inheritance does not work with serialization as well as it should. This is what #75 aims to address. The fix for now is just explicitly saying what `extra_column_attrs` should be in the `SpectroMSMeasurement` class rather than relying on inheritance. This resulted in `spectrum_id` being left out of the dictionary which, as @matenestor noticed, causes some of the errors. It also makes it so that you can't even cut a `SpectroMSMeasurement`!
2. We'll need an extra line or two of code ensuring that the `spectrum_series` attributes are appended when two `SpectroMeasurement`s are appended. This will go here.
3. Adding an `ECMeasurement` and a `SpectroMSMeasurement` is indeed not implemented. We will need a new class named `ECSpectroMSMeasurement` or something like that. Personally, I think it's not a problem - the user does not need to know the name of the calss and if we fix all this ORM inheritance stuff (#75!) then it's cheap to make new classes like this - not much goes in them since they inherit everything, and the most new code that needs to be written is probably just the plotter. (The quicker fix is just to hard-code that we want a plain EC-MS measurement in this case for now.)

I can do a PR with the above three points tomorrow. If you'd like to be sure your exact scripts generating the bugs will run, send or point me to them and the needed data!

A few additional comments here on addition of (Spectro)Measurement objects in ixdat:

The class when adding measurements [is determined](https://github.com/ixdat/ixdat/blob/71cddb1dae19e3c665139f03db2bb0bef5b93b16/src/ixdat/measurements.py#L1326) via the technique, using [get_combined_technique](https://github.com/ixdat/ixdat/blob/71cddb1dae19e3c665139f03db2bb0bef5b93b16/src/ixdat/measurements.py#L1464).

First, I think we need to improve that error message (the one in Anna's opening comment) so that it says what technique it tried to find a class for. Second, we just need to implement some rules for adding techniques with spectra.

if "X" and "Y" are measurement techniques, then:
- "X_spectra" and "Y_spectra" are, by convention, the name of the corresponding spectral techniques, if they exist. There's an "MS_spectra" technique, but no "EC_spectra" technique. (Unfortunately, the class naming is inconsistent: there *is* a `SpectroECMeasurement` which has the same name structure as `SpectroMSMeasurement` but is in fact something different (the spectra are not EC in SpectroECMeasurement)... I think the way to fix this would be to refactor `SpectroMSMeasurement to `MSSpectroMeasurement`. If there are no objections, I will do so in the PR addressing this issue.)
- "X" + "X_spectra" --> "X-X_spectra". this is normal hyphenation, and the reason for an annoyingly-named "MS-MS_spectra" technique in [TECHNIQUE_CLASSES](https://github.com/ixdat/ixdat/blob/71cddb1dae19e3c665139f03db2bb0bef5b93b16/src/ixdat/techniques/__init__.py#L26). 
- If two measurements of the same technique are added, the resulting measurement will always also be of that technique by [this code](https://github.com/ixdat/ixdat/blob/71cddb1dae19e3c665139f03db2bb0bef5b93b16/src/ixdat/measurements.py#L1473) in `get_combined_technique`. 
- "X" + "X-X_spectra" should give "X-X_spectra" by [this code](https://github.com/ixdat/ixdat/blob/71cddb1dae19e3c665139f03db2bb0bef5b93b16/src/ixdat/measurements.py#L1473) in `get_combined_technique` . So adding two `MSSpectroMeasurement`s should give a `MSSpectroMeasurement` .
- Nothing is implemented yet for Y + X-X_spectra, so we'll need to modify in `get_combined_technique` as well to get addition of `ECMeasurement` and `MSSpectroMeasurement` (to a `ECMSSpectroMeasurement` class) working.

**Comment by ScottSoren** [comment]
Okay, I now think I have mostly solved this on the[ spectromeasurements ](https://github.com/ixdat/ixdat/tree/spectromeasurements) branch. I've done points 1, 2, and 4 from my earlier message.

It's demo'd here: https://github.com/ixdat/ixdat/blob/spectromeasurements/development_scripts/reader_demonstrators/demo_zilien_spectrum_reader.py 

@AnnaWiniwarter , can you send me data with which to debug point 3? I need sumultaneous EC data (biologic) and MS data with spectra (zilien). I think I have time to do everything but the plotter, so it'll be just normal EC-MS plots that come from an `ECMeasurement` + `MSSpectroMeasurement`.

@KennethNielsen and @matenestor , all of my development scripts are running on the **spectromeasurements** branch, but some of the --external tests are still failing. I'm inclined to blame the tests. I think you test for a lot of stuff that isn't important, like whether "Ns=0" gets appended to a series list (that has nothing to do with this Issue, but resulted from #134 - I think it's not a problem because e.g. [append_ec_files runs](https://github.com/ixdat/ixdat/blob/spectromeasurements/development_scripts/append_ec_files.py) as it did before). I'll have to take time for each of these failed tests to figure out whether it's overtesting (doesn't matter) or whether something was wrong before or whether something is wrong now. If you have time to diagnose the failing tests with this in mind, that would be greatly appreciated!

In the meanwhile, since I'm also not great at the logic of unit tests, I will prioritize "EC" + "MS-MS_spectra" for Anna, and then the other [issues labeled spectra](https://github.com/ixdat/ixdat/issues?q=is%3Aissue+is%3Aopen+label%3Aspectra), some of which should be quick fixes, to include in the PR.

**Comment by ScottSoren** [comment]
@AnnaWiniwarter , 
Should work now with the code on the[spectromeasurements]https://github.com/ixdat/ixdat/tree/spectromeasurements) branch:
```
ms = Measurement.read("my_zilien_data_with_spectra.tsv")    # an MSSpectroMeasurement
ec = Measurement.read("my_ec_data.mpr")   # a ECMeasurement
ecms = ec + ms      # an ECMSSpectroMeasurement
ecms.plot()              # a normal EC-MS plot
ecms[1].plot()          # a mass spectrum
```

@KennethNielsen , check out [this deleted mess](https://github.com/ixdat/ixdat/commit/e6d5bfec009212b9a7ab9873764bb1202d7dcd13#diff-4f4bb01973e50d003728ed41e7ae32faf9c93b4fa661d6dc665f8153b299da74), and [this class](https://github.com/ixdat/ixdat/blob/e6d5bfec009212b9a7ab9873764bb1202d7dcd13/src/ixdat/techniques/ec_ms.py#L474) which works as intended despite being completely empty! This is a result of the `MemoryBackend` in action, and inheritance actually working just as we want it to at least as far as arguments to `__init__` go. Yours truly, - Happy Developer :)

**Comment by matenestor** [comment]
@ScottSoren tests are now passing in #165. However, using `Measurement.read(technique="EC")` (with `include_mass_scans` set to `True` by default) now raises `TechniqueError`.

**Comment by ScottSoren** [comment]
@KennethNielsen , I think you're right. That would reduce the explosion of classes, and technique names. I can try and make that change in the open PR.
The only challenge that comes to mind right now is the plotter, since these are definitely not empty classes. Should an `MSMeasurement` check whether it has a `spectrum_series` to decide whether it initiates with an `MSPlotter` or a `MSSpectroPlotter`?
