### ISSUE TITLE
Raw_potential=0 for constant current measurements(only) using biologic echem

### ISSUE THREAD

**Issue by JamesMurawski** [ixdat/ixdat#180]
Possible issue with plots(see image) and exported potential data where it will come up with raw_potential=0. Possibly a issue on my end but would be good to know if it can be reproduced. Don't seem to encounter it for other measurement types i.e. CV and constant potential.

![raw_potential=0 issue Figure 2024-06-12 183603](https://github.com/ixdat/ixdat/assets/86737488/8bff590e-a287-4572-acf1-eec117a95ae6)

**Comment by ScottSoren** [comment]
Hi James,
Yes! This is a known (to us at least) issue with the newer EC-Lab versions' exporting of CP data. The zero's are there in the .mpt file, so it's not a parsing issue. It is very annoying.
Two workarounds with ixdat:
- Since v0.2.9, ixdat can import .mpr's, with help of the external packages `eclabfiles` and `galvani` (both pip installable). I think those show the correct potential data. Once you've installed those packages, just switch out ".mpt" with ".mpr" in the file name or extension and it should work: `Measurement.read("my_file.mpr", reader="biologic")` or `Measurement.read_set("my_path", suffix=".mpr", reader="biologic")`
- If you have recorded counter electrode potential, ixdat you can use it with the cell potential (I've not yet seen an issue with either of these in the .mpt files) to calculate the actual WE potential. ixdat makes this easy for you:
```
from ixdat.readers.biologic import fix_WE_potential
fix_WE_potential(my_ec_meas)
```

**Comment by JamesMurawski** [comment]
Hi Soren, 
Thanks for this. Seems that manually exporting the file will work so just a issue with the auto generated .mpt files. But good to know about these other modules!
