### ISSUE TITLE
EC calibration seems to get lost when loading MS calibration

### ISSUE THREAD

**Issue by spoeka22** [ixdat/ixdat#29]
Maybe I'm just calling functions in the wrong way/wrong order, but if I add an MSCalResults object to an ECMSMeasurement object using the following, the previously added EC calibration (for RHE potential and electrode area) get lost.
meas is an ECMSMeasurement:
meas.calibrate(RE_vs_RHE=0, A_el=0.196, R_Ohm=0)
cal_co2 = MSCalResult(name="CO2_M44", mol="CO2", mass="M44", F=F_blank,
            cal_type="internal", )
meas.calibration = ECMSCalibration(ms_cal_results=[calibration])
-> now the EC calibration is gone.

if I add it again, when adding the ms calibration, it works:
meas.calibration = ECMSCalibration(ms_cal_results=[calibration],RE_vs_RHE=0, A_el=0.196)

**Comment by ScottSoren** [comment]
Hey Anna,
Yeah, this is stupid. It's because RE_vs_RHE etc live in meas.calibration. You already found the workaround :D

A real fix is on the way: from the master branch Soon measurements will actually have a list of calibrations, and meas.calibration will group the data in all calibrations in the list. (You'll have to use add_calibration(...) rather than calibration=...)

**Comment by ScottSoren** [comment]
@AnnaWiniwarter , is this okay to close after #50 ?
