### ISSUE TITLE
Create specific data array

### ISSUE THREAD

**Issue by KimDegnJensen** [ixdat/ixdat#37]
All data treatments I have ever worked with is done by exporting/treating a single array of data and then conduct specific analysis (dI/dV or Int I-I0 dV). And array function with interp MXX data for specific conditions, time_span, Ns, cycle number would be really helpful for user doing specialised analysis this function only handles snippets of an experiments and thus it should not be an issue mem.-wise).

**Comment by ScottSoren** [comment]
Hey Kim,

If I understand right here, the question is how to get an array of data out of an ixdat object?

There's a few ways.
The canonical way is to use `Measurement.grab()`. This will give you two arrays - the second is the value that you requested, the first is time. Check the function's documentation - you can do a few things with it including selecting a specific timespan.
For example:
```
from ixdat import Measurement

meas = Measurement.read("my_ec_data.mpt", reader="biologic")
t, v = meas.grab("potential", tspan=[100, 200])

from matplotlib import pyplot as plt
fig, ax = plt.subplots()
ax.plot(t, v)          #  plots potential vs time in the time range 100 s to 200 s
```
If you already know the time vector you want to use, you can use `Measurement.grab_for_t()` and get a single vector out.
For example,  continuing from above:
```
j = meas.grab_for_t("current", t=t)
dQ = np.trapz(j, t)     # integrates the current vector vs the time vector.
```
The most direct way to access a vector with the exact raw data that was in the file is by indexing a measurement to get a `DataSeries`  and taking the `data` attribute (the `t` attribute is the corresponding time):
```
raw_I = meas["I/mA"].data     # a single numpy array with the raw current data
raw_t = meas["I/mA"].t           # the corresponding time data
```
You can check which raw data series are available as arrays by any of the above methods with the `value_names` attribute:
```
print(meas.value_names)
```
This list is not exclusive, as you can also grab calibrated or otherwise derived data series.

If you want to select according to a cycle number, you can use the `select` function to make a smaller measurement, and then get vectors by any of the measurements above:
```
meas_subset = meas.select(Ns=1)    # selects the data where Ns=1
t, dQ = meas.grab("(Q-Q0)/C")         # grabs the cumulative charge passed, and corresponding time as numpy vectors
```
An especially elegant way to select according to cycles is to convert the measurement first to a `CyclicVoltammogram`. Then you can index it with an integer to select a particular cycle.
```
cv = meas.as_cv()
cycle_1 = cv[1]       # selects the first cycle
next_cycles = cv[2:5]    # selects the next five cycles
t, v = next_cycles.grab("potential")
j = next_cycles.grab_for_t("current", j)
fig, ax = plt.subplots()
ax.plot(v, j)          # plot of J vs V for cycles 2 to 5
```

`ixdat` is especially nice with cyclic voltammograbs because it will let you redefine the cycle to select exactly what you want. This is done with the `CyclicVoltammogram.redefine_cycle()` function:
```
cv.plot_measurement(j_name="cycle")     # a plot to see where the cycle presently increments
#  ^ note that j_name is called J_str in ixdat v0.1.x
cv.redefine_cycle(start_potential=0.5, redox=True)    # redefines the `cycle` variable to increment at 0.5 V in anodic direction
cv[2].plot()    # plots J vs V for the second cycle as defined above. You can of course grab data, etc from cv[2]
```
Note that this (and everything here) also works for EC-MS measurements, regardless of whether the EC and MS data were originally read from one file or two file. I like to use the EC program to select cycles, etc, and MS data comes along for the ride.

Finally, you mentioned exporting. You can at any time export a Measurement as a .csv, and specify the column names to export:
```
meas.export("meas_100s_to_200s.csv", tspan=[100, 200]) 
cv[3:6].export("cycles_3_to_6.csv", colums=["potential", "current", "(Q-Q0)/C", "cycle"])
# note, in ixdat v0.1.x, columns is instead called v_list.
```
In the first export, columns for time, potential, and current are included by default. In the second, the desired columns are specified and ixdat automatically makes sure all needed time variables are included.

Keep an eye out for ixdat v0.2.0, as there will be a few minor changes.

I hope that helps! Let me know if there's anything in your question not covered. (If I got everything, please resolve this issue.)

**Comment by ScottSoren** [comment]
@KimDegnJensen , does this answer you question?

**Comment by KimDegnJensen** [comment]
Hi Søren good to hear from you, I think this is exactly what i wanted to
do, I was actually told that my use of grab was ill advised. But now that i
understand a bit more concerning the attributes of the different functions
it all makes a bit more sense, thanks. NB i have a question regarding some
of your old thesis data that we wanted to include in a tech sheet, I would
would prefer to mail it to directly and not through github. could i ask you
to mail me ***@***.*** It concerns soem old CVs of Cu, I believe
these CVs were never published in peer reviewd (i would have expected them
to be in yours and Eijlers paper) and possibly only appears in your thesis.
Hence, i would like to ask if we could use the plots in a tech. sheet,
which ill again prefer to mail to you ensuring that we dont use soemthing
we shouldnt:-)
KR Kim

**Comment by ScottSoren** [comment]
Glad that answered your question. Yeah, `grab` is the cannonical way to get numpy arrays out of ixdat Measurements.

Closing this and replying to you by email :)
