### ISSUE TITLE
Provide easier way to see series names (and aliases w. relations), possibly as an implementation of a multiline Measurement.__str__

### ISSUE THREAD

**Issue by KennethNielsen** [ixdat/ixdat#67]
In a discussion with @AnnaWiniwarter it came up that there is sometimes a bit of searching involved to find the series names to use. It is provided as `Measurement.get_series_names`, but as far as getting information easily, nothing beats printing the object out. Therefore, I suggest solving this by making a comprehensible `Measurement.__str__` implementation that would conveniently show series names, aliases to the same and possibly the route over calibrations, imagine something like

```text
ECMS measurement with 10 value series.

Series list:
┏ 'Time [s]'                                                     ╺╺╺ Span: 1..3681s
┗━ 'MFC1 value [ml/min]' (or 'MFC1 value point' or 'MFC1 vp')    ╺╺╺ Span: 1..10 ml/min
┏ 'Time [s]'                                                     ╺╺╺ Span: 41..121s
┣━ 'Ewe / V' or 'Ewe'                                            ╺╺╺ Span: -1.2..1.2 V
┣━ 'I / mA'                                                      ╺╺╺ Span: -50.2..130 mA
┣━ 'cycle number' (or 'cycle_n')                                 ╺╺╺ Span: 1..40 n
┗━ 'potential' via Calibration(RE_vs_RHE=1.2, A_el=3.4) of 'Ewe / V' ╺╺╺ Span: -1.4..1.0 V

```
or
```text
ECMS measurement with 10 value series.

Series list:
┏ 'Time [s]'                                                     ╺╺╺ Span: 1..3681s
┗━ 'MFC1 value [ml/min]' (or 'MFC1 value point' or 'MFC1 vp')    ╺╺╺ Span: 1..10 ml/min
┏ 'Time [s]'                                                     ╺╺╺ Span: 41..121s
┣━ 'Ewe / V' or 'Ewe'                                            ╺╺╺ Span: -1.2..1.2 V
┣━ 'I / mA'                                                      ╺╺╺ Span: -50.2..130 mA
┣━ 'cycle number' (or 'cycle_n')                                 ╺╺╺ Span: 1..40 n
┗━ 'potential' via ↴                                   ↱         ╺╺╺ Span: -1.4..1.0 V
              Calibration(RE_vs_RHE=1.2, A_el=3.4) of 'Ewe / V' 
```
or something entirely different. In both cases above I have emphasized English over syntax i.e. `or` instead of `alises: ["...", "..."]` and `via` ... `of` etc. and I have to various degress used unicode symbols to draw meaningful diagrams of ValueSeries pointing to the same TimeSeries. But this is a just a programmers view on how this might look. Feedback very much welcome (@AnnaWiniwarter and anyone else).

And @ScottSoren, I of course also want your opinion on:

1. Implementing `__str__`, which will then mean that printing the Measurement objects will no longer default to the __repr__, but this can still be reached by print(repr(obj)). It might also optionally be included as the first or second line in the `__str__`. But generally I think the `__repr__`'s are more for programmers 
2. Implementing it as a multi-line return, which isn't done a lot but I don't think is particularly controversial if there is a good reason for it. Personally I'm all for ;)

Another idea here, would be to also implement `__str__` of the Series as something like `TimeSeries: 1..3681s`, `ValueSeries: 1..40n` which makes sense in their own right and which can then be injected after the `╺╺╺` above for re-use.

**Comment by ScottSoren** [comment]
Love it. I think this is definitely missing! 

It's a challenge to implement, though, right, because of the need to check all the calibratons' `get_calibrated_series` functions and figure out the names of what calibrated series they can return?  The `series_list` and the `aliases`, yes (especially becasue there's already a `revers_aliases` property), but the calibrations... I assumed that was not practically possible.

It seems both questions are about whether it belongs in `__str__` . I think it does not belong there :( . I think str(obj) should be a one-liner because I often use them in error messages, etc. For example, the last resort of `Measurement.get_series` (and thus of `__getitem__`) is:
```
        raise SeriesNotFoundError(f"{self} does not contain '{key}'")
```
This is a disaster if str(self) is a report of all of the measurement's contents. I just thecked and f-string uses str(obj) rather than repr(obj):
```
>>> class A:
...     def __repr__(self):
...         return("obj of class A")
...     def __str__(self):
...         return("a sample object of my sample class")
>>> a = A()
>>> str(a)
'a sample object of my sample class'
>>> repr(a)
'obj of class A'
>>> f"{a}"
'a sample object of my sample class'
```
So, to preserve the ability to have a one-line representations in f-strings, I think the report you describe here should go somewhere else.

**How about `print(Measurement.description)` or `Measurement.print_contents()`?**

Including the `span` in the `__str__` of the DataSeries seems a good idea. But it's `[data[0], data[-1]]`, not `[min(data), max(data)]` which is in general different except for `TimeSeries`. Will that throw people off? And,since `print(data_series.data)` gives the numpy string representation, which includes the endpoints, is it necessary?

**Comment by KennethNielsen** [comment]
> It's a challenge to implement, though, right, because of the need to check all the calibratons' get_calibrated_series functions and figure out the names of what calibrated series they can return?

I wasn't aware of the practical implications with the calibrations, but I will take your word for it.

> It seems both questions are about whether it belongs in __str__ . I think it does not belong there :( . I think str(obj) should be a one-liner because I often use them in error messages, etc. For example, the last resort of Measurement.get_series (and thus of __getitem__) is:

        raise SeriesNotFoundError(f"{self} does not contain '{key}'")

> This is a disaster if str(self) is a report of all of the measurement's contents. I just thecked and f-string uses str(obj) rather than repr(obj):

I'd like to challenge that. Yes, `f"{obj}"` returns the `__str__` but `f"{obj!r}"` returns the `__repr__`, so it might not be bad to get in the habit of using that instead. I think it fundamentally comes down to whether the `__str__` should serve the needs of the user or of the developers and I would tend to favor the users there, because nothing is a discoverable as `print(obj)`.

> How about print(Measurement.description) or Measurement.print_contents()?

Could work as well, just not as discoverable IMO, see above.

> Including the span in the __str__ of the DataSeries seems a good idea. But it's [data[0], data[-1]], not [min(data), max(data)] which is in general different except for TimeSeries. Will that throw people off? And,since print(data_series.data) gives the numpy string representation, which includes the endpoints, is it necessary?

WRT the `.data` option again I think it is about discoverability. `__str__` should be the _string representation of the object_. To me it makes sense to include essential summary data in that, if possible. WRT to what information to display, I actually specifically wanted to show `min(data)` and `max(data)`, because that holds better information for more series. For a time series, it will still show the span, so great, that is what we want to know about that, but for e.g. mass series, we will immediately know how large of a signal we are in general looking at and for the potential of a CV you will immediately get two of the primary settings you identify a CV with, whereas [0] and [-1] will most likely get you zero worth-while information. The trick is to find a good (understandable) syntax for the min max values. Could be something with arrows, like `TimeSeries: ▼1▲3681s` or `TimeSeries: ↓1↑3681s`.

**Comment by AnnaWiniwarter** [comment]
Just to chime in here from the user's perspective: What I've experienced as problematic (and I believe also Kim has been struggling with this) is that from the objects themselves it's really hard to understand what kind of information there is in there and how to get it out. 
If I take a dictionary, or a pandas `DataFrame` (or a numpy array for that matter) and I print it, I get all the info I need to call columns etc. If I take an` ECMSMeasurement` object and I print it, I only get the info of which files were read in to generate the object. This IS interesting and relevant info, but it doesn't help me to continue with my data treatment. If I now have something like `print(Measurement.description) or Measurement.print_contents()` that's nice, but I will have to read enormous amounts of documentation to figure that out, and frankly, noone will do that. 

I've had plenty of discussions with Kim who is really challenging the usefulness of ixdat, because he feels like he doesn't know where the data is. He is used to working with arrays and selecting rows and columns according to indices. I think we can convince him that using ixdat will make his life easier than this, by providing the possibility of choosing specific CV cycles or the current in a specific `tspan` ONLY if we also provide an easy and intuitive way of figuring out what data there is in a `Measurement` object. And I agree with Kenneth that printing the object is simply the most straightforward easy way.

**Comment by KennethNielsen** [comment]
@ScottSoren @AnnaWiniwarter I should probably input a little more here, as a statement somewhere in between user and developer, with regards to the point that @AnnaWiniwarter raises about the amount of required reading to get started and be able to discover useful things. Personally, I don't think that that amount needs to be zero and it definitely shouldn't be "huge amounts" either. To "get started, know the basics and be able to do useful stuff" I think a reasonably length tutorial is about right. So, **if** we implement the `.description` for all relevant objects (which could reasonably be done) and it is shown in the first tutorial as _the_ way to discover available series from a measurement, then for me that _could_ be an acceptable solution. 

The reason that I'm opening a little up for that solution, which isn't necessarily clear from the above, is that the change I suggested with `f"{obj!r}"` is pretty invasive and might be forgotten in future development, so it might be a little fragile.

**Comment by AnnaWiniwarter** [comment]
fair enough, I can accept that. As long as we figure out a way to provide like a "quick start guide" to ixdat. Which I think should be there in addition to a tutorial. Maybe just a list of "most common commands" or something like this.

**Comment by KennethNielsen** [comment]
@AnnaWiniwarter that is an excellent idea, or like a "cheat sheet".

**Comment by ScottSoren** [comment]
Ah, I hadn't realized #37 was about how to figure out what data was called - then my long answer there was beside the point.

I should have answered that raw data series names are always listed in `meas.value_names`, and that for the rest, you do need to know something about how the `Measurement` class and its `Calibrations` behave (like the fact that you can always look up `raw_potential`, `raw_current` , `potential` and `current` in an `ECMeasurement`, which is documented in the class docstring but maybe that's not the first place you look). I absolutely agree it something like this is missing. As for where:

- @AnnaWiniwarter , pandas DataFrame is a very good example - that does indeed print everything in the str, and that is useful.
- And @KennethNielsen , I didn't know about the `f"{obj!r}"`. I think that is not so bad to put into f-string error and warning messages. 

So... @both, I'm convinced. This is a good idea and `__str__` is the best place to implement it for ease of use.
