### ISSUE TITLE
Measurement.select_values() doesn't work as expected

### ISSUE THREAD

**Issue by AnnaWiniwarter** [ixdat/ixdat#72]
I would like to select a subsection of my ecms object based on the selector "Ns". It shows the expected values when plotting with ecms.plot_measurement(), but when trying to use ecms.select_values() no matter what I choose as value it will always return a very small subsection of the data (see below)
![image](https://user-images.githubusercontent.com/96479350/168810147-494541c9-c543-44a0-865f-78edc9178bb8.png)

**Comment by AnnaWiniwarter** [comment]
Also, the thing with the aliases doesn't quite work the way I would expect - why can I not call "time/s" even if it's listed as alias?
![image](https://user-images.githubusercontent.com/96479350/168811242-72ab13ac-c94e-4286-b1af-7cf798ea5274.png)

**Comment by ScottSoren** [comment]
Fine to take both bugs here.

With the first bug, I think it is your use of `select_values`. 
I think the syntax should be 
`h2_F_list[0].select_values(Ns=1)`
with Ns not a string and a single equals sign. In your syntax, `select_values` gets as its input the Boolean value `False` (because "Ns" does not equal 1).

The way the `select_values` method works is that it takes any key-word argument by using the `**kwargs` trick), which then converts the key-word arguments you give it to a dictionary, here `{"Ns": 1}`. I guess maybe it is a little bit black magic which should be better documented - what do you think?

The second thing might be more of an ixdat bug, if it causes problems independent of the first bug. But I think it is related to #71. It looks like this is an `ECMSMeasurement` made by adding a zilien-imported `ECMSMeasurement` which originally had EC data with one or more `ECMeasurement`s. Try instead importing the zilien data as an `MSMeasurement`. "Potential time [s]" should then not appear in the aliases for "t".

**Comment by ScottSoren** [comment]
Added example usage to docstring [here](https://github.com/ixdat/ixdat/pull/73/files#diff-43ab64d9e181053cbec41dc789f0e00293a42363384406c80bcd1283a3872571)

**Comment by AnnaWiniwarter** [comment]
Ok, the syntax was not clear to me, because I was not aware of this `**kwargs` trick. Using the correct syntax works for me, but it makes the method I wrote look really ugly. I will make a PR with this, let's take the discussion there. 
And you're right. If I import the Zilien file as MSMeasurement, then it does not contain "Potential time [s]" in aliases, and calling "time/s" works.
