### ISSUE TITLE
Mismatch of raw and parsed values

### ISSUE THREAD

**Issue by matenestor** [ixdat/ixdat#87]
There is a mismatch of values, that we had recorded during a measurement with CA technique, and those parsed by Ixdat from mpt files later. The files, that the tests does not pass for, are [here (05_CA)](https://github.com/ixdat/ixdat-large-test-files/blob/main/multiple_techniques_dataset/multiple_techniques_dataset_01_05_CA_C01.mpt) and [here (06_CA)](https://github.com/ixdat/ixdat-large-test-files/blob/main/multiple_techniques_dataset/multiple_techniques_dataset_01_06_CA_C01.mpt).

The mismatch is in the column `cycle number` (penultimate), which is created as a `ConstantValue`. In the raw file the `cycle number` is being incremented from zero to one (in the first 05_CA file) and from zero to five (in the second 06_CA file). Ixdat returns the columns with all zero values. Even when I rewrote all 0s in the column to 1s, the Ixdat still parsed it as 0s.

Dataset was recorded without EC-lab loops feature. However, we don't fully understand what could be the cause. It could be a mistake in the dataset itself. So for now, we need more information.

**Comment by ScottSoren** [comment]
The problem is in readers/biologic.py lines 177-186. That code is there because all biologic ECMeasurements need a `cycle number` and `Ns` in order for the `selector` to be built correctly when these files are appended. However, for some reason, I hard coded which types of .mpt files have and don't have those files rather than just checking for it. I am a bit surprised to see "CA" files with "Ns" _and_ "cycle number", which is what makes the bug apperent here. Usually they just have "Ns" - maybe that's changed with a new ECLab version or something.

I've fixed it here: https://github.com/ixdat/ixdat/commit/93b3c6be0b097564ee5667f45c1c8263eff93d74
