### ISSUE TITLE
make plotting terminal friendly

### ISSUE THREAD

**Issue by matenestor** [ixdat/ixdat#89]
When I want to plot a measurement, I call `my_measurement.plot()`. In the jupyter notebook it shows the plot by default, however in my terminal, where I use pure IPython, I have to call `plt.show()` from the matplotlib. It would be nice if the plotter also called `plt.show()`, besides returning a list with two `AxesSubplot` objects.

**Comment by ScottSoren** [comment]
Ah, good point. But I think it's best not to have plt.show() built into ixdat code, since in some environments it pauses a script until the plot that is being shown is closed by the user. This is annoying if the script is being used to e.g. prepare a figure for a presentation.
I do almost all of my work in Spyder and PyCharm, which show all figures at the end of execution of a script.
I think it's easier for the terminal user to type plt.show(), as they would if just using matplotlib, rather than for the Spuder/Pycharm user to have a stutter in their workflow.

**Comment by matenestor** [comment]
True, I did not realize that. And a check for running environment would not help, because Spyder is running IPython as well, but still shows the plot without pause, so it has to be hacking it internally somehow.

I will create a function that will call both `my_measurement.plot()` and `plt.show()` together.. calling `my_measurement.plot(terminal=True)`, or similar, would be the same amount of work. :smile:
